replicaCount: 2

image:
  repository: andygolubev/eks-demo-frontend
  tag: "sha-97b4f6c"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

gateway:
  enabled: true
  name: argocd-gateway
  namespace: argocd
  hostname: front.064083568243.realhandsonlabs.net
  httpListenerName: http
  httpsListenerName: https
  enableHttps: true
  targetType: ip
  healthCheckPath: /healthz
  annotations: {}
